import NAAC from "../../../assets/HomePage/AffiliationIcons/NAAC.svg";
export const AffiliationData = [
  {
    id: 0,
    icon: NAAC,
    category: "college",
    title: "NAAC Accredited",
    points: "A+ Grade",
    text: "Nationally assessed by the National Assessment and Accreditation Council for academic excellence",
    since: "2019",
  },
  {
    id: 1,
    icon: NAAC,
    category: "HOSPITAL",
    title: "NABH Certified",
    points: "Full Accreditation",
    text: "Recognised by the National Accreditation Baard for Hospitals. for quality patient care standards.",
    since: "2021",
  },
  {
    id: 2,
    icon: NAAC,
    category: "both",
    title: "ISO Certified",
    points: "A+ Grade",
    text: "Nationally assessed by the National Assessment and Accreditation Council for academic excellence",
    since: "2019",
  },
  {
    id: 3,
    icon: NAAC,
    category: "COLLEGE",
    title: "NAAC Accredited",
    points: "A+ Grade",
    text: "Nationally assessed by the National Assessment and Accreditation Council for academic excellence",
    since: "2019",
  },
  {
    id: 4,
    icon: NAAC,
    category: "COLLEGE",
    title: "NAAC Accredited",
    points: "A+ Grade",
    text: "Nationally assessed by the National Assessment and Accreditation Council for academic excellence",
    since: "2019",
  },
  {
    id: 5,
    icon: NAAC,
    category: "COLLEGE",
    title: "NAAC Accredited",
    points: "A+ Grade",
    text: "Nationally assessed by the National Assessment and Accreditation Council for academic excellence",
    since: "2019",
  },
  {
    id: 6,
    icon: NAAC,
    category: "COLLEGE",
    title: "NAAC Accredited",
    points: "A+ Grade",
    text: "Nationally assessed by the National Assessment and Accreditation Council for academic excellence",
    since: "2019",
  },
  {
    id: 7,
    icon: NAAC,
    category: "COLLEGE",
    title: "NAAC Accredited",
    points: "A+ Grade",
    text: "Nationally assessed by the National Assessment and Accreditation Council for academic excellence",
    since: "2019",
  },
];
